package com.huntmaster;

/** Packaged collection scope, not assignment-credit policy. No remote code or identifiers. */
final class SupportedEncounters {
 private SupportedEncounters() {}
 static final String[] NAMES = {"Vardorvis",
"Duke Sucellus",
"The Leviathan",
"The Whisperer",
"Zulrah",
"Vorkath",
"Phantom Muspah",
"Phosani's Nightmare",
"Amoxliatl",
"The Gauntlet",
"Doom of Mokhaiotl",
"Obor",
"Bryophyta",
"Moons of Peril",
"Barrows Brothers",
"Brutus",
"Deranged Archaeologist",
"Maggot King",
"Mad Angel",
"The Corrupted Gauntlet",
"Hespori",
"Skotizo",
"The Mimic",
"TzTok-Jad",
"TzKal-Zuk",
"Sol Heredit",
"General Graardor",
"Commander Zilyana",
"K'ril Tsutsaroth",
"Kree'arra",
"Corporeal Beast",
"Sarachnis",
"Giant Mole",
"Kalphite Queen",
"The Hueycoatl",
"The Nightmare",
"Yama",
"Scurrius",
"Wintertodt",
"Tempoross",
"Zalcano",
"Royal Titans",
"Nex",
"Abyssal Sire",
"Alchemical Hydra",
"Araxxor",
"Cerberus",
"Grotesque Guardians",
"Kraken",
"Thermonuclear Smoke Devil",
"Shellbane Gryphon",
"Artio",
"Callisto",
"Calvar'ion",
"Vet'ion",
"Spindel",
"Venenatis",
"Chaos Elemental",
"Chaos Fanatic",
"Crazy Archaeologist",
"King Black Dragon",
"Scorpia"};
}
