displayName=Huntmaster
author=DxewRS
description=Exclusively for Bosscape's Huntmaster Discord Bot, used to verify bossing kills
tags=boss,kc,discord,huntmaster
version=
plugins=com.huntmaster.HuntmasterPlugin
build=standard
